name: Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a feature! Please note that this is an educational project with specific constraints:
        - Phase 1-3 budget: $0/month (local development only)
        - Phase 4-5 budget: $200/month maximum (Azure production)
        - Must align with AGNTCY SDK patterns
        - Should enhance educational value

  - type: dropdown
    id: phase
    attributes:
      label: Target Phase
      description: Which phase should this feature be implemented in?
      options:
        - Phase 1 - Infrastructure & Containers
        - Phase 2 - Business Logic
        - Phase 3 - Testing & Validation
        - Phase 4 - Azure Production Setup
        - Phase 5 - Production Deployment
        - Future Enhancement (beyond Phase 5)
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Component Category
      description: Which area does this feature affect?
      options:
        - Agent Implementation
        - Mock API
        - Infrastructure
        - Observability
        - Testing
        - CI/CD
        - Security
        - Documentation
        - Cost Optimization
        - Multi-Language Support
        - Other
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? Is your feature request related to a problem?
      placeholder: |
        I'm frustrated when... / It would be useful if...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see
      placeholder: |
        The feature should...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions or features?
      placeholder: |
        Alternative approach 1...
        Alternative approach 2...

  - type: dropdown
    id: educational-value
    attributes:
      label: Educational Value
      description: Does this feature enhance the educational value of the project?
      options:
        - High - Demonstrates important concepts
        - Medium - Useful but not critical for learning
        - Low - Nice to have
    validations:
      required: true

  - type: dropdown
    id: budget-impact
    attributes:
      label: Budget Impact (Phase 4-5 only)
      description: Will this feature affect the $200/month Azure budget?
      options:
        - No cost impact (Phase 1-3 or free services)
        - Low cost (<$10/month)
        - Medium cost ($10-50/month)
        - High cost (>$50/month)
        - Unknown - needs estimation
    validations:
      required: true

  - type: textarea
    id: implementation
    attributes:
      label: Implementation Approach
      description: How would you implement this? (optional but helpful)
      placeholder: |
        1. Add new agent type...
        2. Integrate with...
        3. Update configuration...

  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance Criteria
      description: How will we know when this feature is complete?
      placeholder: |
        - [ ] Feature works as described
        - [ ] Tests added with >80% coverage
        - [ ] Documentation updated
        - [ ] Budget constraints respected
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature?
      options:
        - Critical - Blocks progress
        - High - Important for project goals
        - Medium - Nice to have
        - Low - Future enhancement
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context, mockups, or examples
      placeholder: |
        Related issues, links to similar implementations, etc.

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      options:
        - label: I have searched existing issues and PRs to avoid duplicates
          required: true
        - label: This feature aligns with the educational goals of the project
          required: true
        - label: I have considered the budget constraints ($200/month for Phase 4-5)
          required: true
        - label: This feature respects AGNTCY SDK integration patterns
          required: true
